### ISSUE TITLE
请问如何保留--flow 功能呢

### ISSUE THREAD

**Issue by jt8823** [Qetesh/logi-options-plus-mini#1]
我删除了脚本中的 --flow  no   flow出现了，但是无法和我安装的windows原版logi，进行互通，是不是还依赖其它服务被禁用了呢？

**Comment by Qetesh** [comment]
实测macOS15与Windows11，使用删除脚本`--flow no`后可以和Windows互通。btw，Windows也可以通过安装参数精简功能，Windows也是精简后只保留flow安装的。macOS需要网络的局域网权限，可以检查一下
后续计划添加Windows适用的安装脚本

**Comment by jt8823** [comment]
哦哦哦。 谢谢，  他没有提醒了需要局域网权限，  我忘记这个开关了，   现在开开就好了，  我刚才尝试了下，用  gpt  去修改您的脚本，让windows也能用，  然而失败了，   haha

># Define variables
$package = "logioptionsplus_installer"
$downloaded_path = "C:\Temp\logioptionsplus"
$downloaded_package_path = "$downloaded_path\$package.zip"
$package_unarchived_path = "$downloaded_path\$package"
$weburl = "https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.zip"
$appname = "Logi Options+"
$installer_name = "logioptionsplus_installer.exe"

Write-Output ""
Write-Output "##############################################################"
Write-Output "$(Get-Date) | Starting install of $appname"
Write-Output "############################################################"
Write-Output ""

# Create download path if it doesn't exist
if (Test-Path -Path $downloaded_path) {
    Write-Output "$(Get-Date) | Cleaning up previous cache."
    Remove-Item -Recurse -Force $downloaded_path
}

Write-Output "$(Get-Date) | Creating $downloaded_path directory..."
New-Item -Path $downloaded_path -ItemType Directory

# Download the Installer
Write-Output "$(Get-Date) | Downloading $appname Installer..."
Invoke-WebRequest -Uri $weburl -OutFile $downloaded_package_path

# Unzip the Installer
Write-Output "$(Get-Date) | Unzipping $downloaded_package_path to $downloaded_path..."
Expand-Archive -Path $downloaded_package_path -DestinationPath $downloaded_path

# Run the installer
Write-Output "$(Get-Date) | Installing $appname..."
$install_command = "$package_unarchived_path\$installer_name"

# Execute the installer (Assuming the installer has similar options)
Start-Process -FilePath $install_command -ArgumentList "--analytics No --sso No --update No --dfu No --logivoice No --aipromptbuilder No --device-recommendation No" -Wait

# Check the exit code
if ($LASTEXITCODE -eq 0) {
    Write-Output "$(Get-Date) | $appname Installed successfully."
    Write-Output "$(Get-Date) | Cleaning Up"
    Remove-Item -Recurse -Force $downloaded_path
    Write-Output "$(Get-Date) | $appname Installed successfully."
    exit 0
} else {
    Write-Output "$(Get-Date) | Failed to install $appname"
    exit -1
}

**Comment by Qetesh** [comment]
https://github.com/Qetesh/logi-options-plus-mini/commit/a50c338f72f661b4090936f513e586b874a7262d
已添加Windows系统PowerShell脚本，需要的话可以试一下
