### ISSUE TITLE
gpw无法连接 macos

### ISSUE THREAD

**Issue by suntoryl2** [Qetesh/logi-options-plus-mini#2]
用数据线或接收器都无法连接

**Comment by Qetesh** [comment]
感谢反馈

gpw属于罗技 G系列，配套软件是Logitech G HUB

官方下载链接https://www.logitechg.com/zh-cn/innovation/g-hub.html

**Comment by suntoryl2** [comment]
官方那个难用，不是登录不上，就是读取不了设备，感谢你的推荐

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Qetesh ***@***.***&gt;
发送时间: 2024年12月11日 15:38
收件人: Qetesh/logi-options-plus-mini ***@***.***&gt;
抄送: suntoryl2 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Qetesh/logi-options-plus-mini] gpw无法连接 macos (Issue #2)





 
感谢反馈
 
gpw属于罗技 G系列，配套软件是Logitech G HUB
 
官方下载链接https://www.logitechg.com/zh-cn/innovation/g-hub.html

**Comment by Qetesh** [comment]
G系列鼠标支持板载内存模式

将配置写入鼠标，就可以卸载G HUB了

**Comment by suntoryl2** [comment]
好的 感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Qetesh ***@***.***&gt;
发送时间: 2024年12月11日 15:45
收件人: Qetesh/logi-options-plus-mini ***@***.***&gt;
抄送: suntoryl2 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Qetesh/logi-options-plus-mini] gpw无法连接 macos (Issue #2)





 
G系列鼠标支持板载内存模式
 
将配置写入鼠标，就可以卸载G HUB了
